# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import getid_pb2 as getid__pb2


class GenIdStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetId = channel.unary_unary(
                '/GenId/GetId',
                request_serializer=getid__pb2.GetRequest.SerializeToString,
                response_deserializer=getid__pb2.IdReply.FromString,
                )


class GenIdServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetId(self, request, context):
        """simple rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenIdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetId,
                    request_deserializer=getid__pb2.GetRequest.FromString,
                    response_serializer=getid__pb2.IdReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GenId', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenId(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GenId/GetId',
            getid__pb2.GetRequest.SerializeToString,
            getid__pb2.IdReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
